// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPfLjEvyESUcmS-YmEjT1LaW_rqa6pGsQ',
    appId: '1:942444239780:web:0797c085d8ec8079517f31',
    messagingSenderId: '942444239780',
    projectId: 'labubucas',
    authDomain: 'labubucas.firebaseapp.com',
    storageBucket: 'labubucas.firebasestorage.app',
    measurementId: 'G-ZYGX9FS33M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBByMXoZuSy_N7SRDvvwEfvRcrsv-siOUk',
    appId: '1:942444239780:android:b7efdc7a5d3359f7517f31',
    messagingSenderId: '942444239780',
    projectId: 'labubucas',
    storageBucket: 'labubucas.firebasestorage.app',
  );
}
